### ISSUE TITLE
Wrong type argument: listp, -21600

### ISSUE THREAD

**Issue by byorgey** [mbork/beeminder.el#1]
I think I have beeminder.el successfully installed, but when I try running `beeminder-list-goals`, I get an error message

```
Wrong type argument: listp, -21600
```

and the resulting beeminder buffer just looks like this:

```
Beeminder goals for user byorgey
sorting criterion: losedate
filters: none
```

with no goals listed.  Any ideas what could be the problem?

**Comment by byorgey** [comment]
I should add that I have GNU Emacs 24.4.1, and am sure that I am using the most up-to-date version of beeminder.el.

**Comment by byorgey** [comment]
@mbork do you have any suggestions?  I am still getting this error even after pulling all the most recent commits.

**Comment by mbork** [comment]
Well, I haven't tested beeminder.el on Emacs 24 (I've been on Emacs 25 for several months now). Could you try M-x set-variable RET debug-on-error RET t RET and tell me what's happening? (I'll have some time tomorrow, maybe I'll try to install an older Emacs and test it there, too.)

And sorry for not responding earlier - somehow I missed your problem (I didn't get any emails about it until now).

**Comment by byorgey** [comment]
No worries about not responding earlier --- github's notification settings are less than transparent.  I wondered if it might be something like that which is why I added a comment mentioning your username.

Anyway, here's what I get when I enable debug-on-error: http://lpaste.net/2391044702120968192 . Happy to provide any other info to help figure this out.

**Comment by mbork** [comment]
@byorgey try now. I'm almost sure that is the Emacs 24/25 issue. (I used an undocumented feature of time-add, which was quite handy, but I guess it was introduced after your Emacs version.)

**Comment by byorgey** [comment]
@mbork Progress!  Now I get a different error: http://lpaste.net/4038844759618355200 .

**Comment by mbork** [comment]
That is extremely uncool. It turns out that the alist-get function is also new. I will fix it, but it's not as fast as the previous problem. My fault; I should have installed Emacs 24 (or maybe even Emacs 23) and tested there. Stay tuned, hopefully I'll be able to fix this today.

**Comment by byorgey** [comment]
No worries, thanks!

**Comment by mbork** [comment]
On 2015-10-02, at 13:36, Brent Yorgey notifications@github.com wrote:

> No worries, thanks!

Hi there,

I finally compiled Emacs 24.1 so that I could test beeminder.el there.

Bad news are that it turned out that I rely on quite a few Emacs 25
features (although it's also quite possible that Emacs 24.3 would
suffice, I don't know that yet).

Good news is that there are two possible solutions.  One is me adapting
beeminder.el to older Emacs.  This would take some time - I started
giving classes at my university, and I have quite a lot of them this
semester, so my coding time will shrink considerably.  I guess one week
is a reasonable minimum.

Another one is you compiling Emacs 25.  While it may sound daunting, it
is really a painless process: probably the most time-consuming part is
getting all the dependencies, and even that took like 15 minutes on my
Ubuntu box and a similar time on Fedora.  Then, it is a question of
doing

./autoconf.sh
./configure
make

and optionally

sudo make install

So, if you are impatient, you may try compiling a bleeding edge Emacs
(and it might be worthwhile anyway), and if not, just drop me a note so
that I know that I should start working on adapting beeminder.el to
older Emacsen.

Best, and sorry for the inconvenience

## 

Marcin Borkowski
http://octd.wmi.amu.edu.pl/en/Marcin_Borkowski
Faculty of Mathematics and Computer Science
Adam Mickiewicz University

**Comment by byorgey** [comment]
No worries, thanks for looking into this.  Building Emacs 25 doesn't scare me, I'll give it a whirl sometime soon.

**Comment by mbork** [comment]
On 2015-10-08, at 17:21, Brent Yorgey notifications@github.com wrote:

> No worries, thanks for looking into this.  Building Emacs 25 doesn't scare me, I'll give it a whirl sometime soon.

You may also try the newest version.  I haven't test it very extensively
in Emacs 24.1.1 yet, but the main features seem to work.  (Of course, if
you encounter any weird behavior, report it as soon as possible.  Also,
you might want to set debug-on-error to t, at least for some time.)

By the way, while playing around with beeminder.el on Emacs 24,
I discovered a few bugs, so thanks for your input - it helped even for
the Emacs 25 experience!

Best,

## 

Marcin Borkowski
http://octd.wmi.amu.edu.pl/en/Marcin_Borkowski
Faculty of Mathematics and Computer Science
Adam Mickiewicz University
