### ISSUE TITLE
Please List dependencies in Readme

### ISSUE THREAD

**Issue by Zacharius** [mbork/beeminder.el#3]
I had to install the packages reqeust, anaphora, and require the package cl before I could get yours to work. Mentioning these in the readme might be useful.

I appreciate the work you do, just started using this but it seems good.

**Comment by mbork** [comment]
Thanks. I have updated the readme wrt `request` and `anaphora`.
The code should require `cl` itself. Which Emacs version do you use? What happens if you do not require it?

**Comment by Zacharius** [comment]
Hi mbork! sorry for the late reply. I was using emacs24, which is apparently the default package in debian. I changed to 25 when even after i got your package to load without errors I still couldn't use it because the datapoints wouldn't upload to beeminder. Changing to 25 fixed that issue.

without require cl, I will get the error "Symbol's function definition is void: caddr" when I run beeminder-list-goals. This problem persists in emacs25

As for the other packages, request and anamphora. I cant seems to replicate the errors I was getting and your package seems to work fine without them. Maybe the functions requiring those packages were only called during an initialization process? IDK?

Been using your package to log all my beeminder goals and things are going very well. Thanks for making it.

**Comment by mbork** [comment]
On 2018-06-19, at 17:51, Zacharius <notifications@github.com> wrote:

> Hi mbork! sorry for the late reply. I was using emacs24, which is apparently the default package in debian. I changed to 25 when even after i got your package to load without errors I still couldn't use it because the datapoints wouldn't upload to beeminder. Changing to 25 fixed that issue.

Glad to hear that!  Although I'd like to know what caused the problem
(see below)...

> without require cl, I will get the error "Symbol's function definition is void: caddr" when I run beeminder-list-goals. This problem persists in emacs25

I see.  I cannot reproduce this, since I don't have an emacs25 here (and
it's not trivial to get it running, since my init.el is incompatible
with it - and emacs25 -q is not very useful w/o packages etc.).  I think
I'll try to install docker or something to be able to run older emacsen
(my Emacs says it's 27.0.50...) - but that will have to wait until I get
back from vacation.

You might want to (require 'subr) instead of cl - I would guess subr is
smaller than cl.  Though I don't see any reason not to have cl required
anyway.

> As for the other packages, request and anamphora. I cant seems to replicate the errors I was getting and your package seems to work fine without them. Maybe the functions requiring those packages were only called during an initialization process? IDK?

request is definitely necessary, since it is used to issue, well, http
requests to the Beeminder server.  anaphora is also used (I use the aif
macro from that package), though I define it myself if emacs version is
at least 24.  (That condition is pretty strange, and I guess I'll have
to sort it out in a cleaner way.  Again, after vacation, I guess.)

> Been using your package to log all my beeminder goals and things are going very well. Thanks for making it.

You're welcome!  I'm glad you like it.  Frankly speaking, it would
benefit from a major rewrite (I was much more of a beginner when I wrote
it), but it works, so I don't fix it;-).  (In fact, I have lots of
things to do and limited time, so...)

If you have any other problem with beeminder.el, don't hesitate to write
me an email or create an issue on GitHub!  I'll try to find time anyway
if the thing is important.  Also, if you have any feature request, don't
hesitate - I might be tempted to implement it!

Best,

--
Marcin Borkowski
http://mbork.pl
